### ISSUE TITLE
UI Work

### ISSUE THREAD

**Issue by shamshirz** [SylverStudios/WatchWithMe#27]
Acceptance Criteria:
 - Spikes or separate issues created for some of these issues

Possible Issues:
 - Create a UI widget to show on the page
 - Display useful info in the Browser Action
 - Reactify the Browser Action
 - Maybe add toast messages for when actions happen
    - This might be good, so when you receive a command, there is a little toast

**Comment by samgqroberts** [comment]
an initial spike here has happened -- going to close in favor of more targeted issues
