### ISSUE TITLE
Remove messaging from server side

### ISSUE THREAD

**Issue by shamshirz** [SylverStudios/WatchWithMe#31]
The direct string messages were a great way to start, but I don't think I need them anymore

The server has a responsibility to reduce incoming actions and broadcast them, it's job is not to interpret the meaning of those messages and craft a user friendly text.

**Comment by samgqroberts** [comment]
@shamshirz thoughts on this?

**Comment by shamshirz** [comment]
closing, probs closing most. If it's a real issue, it will rear up again
