### ISSUE TITLE
Migrate Codeship

### ISSUE THREAD

**Issue by rjdellecese** [SylverStudios/WatchWithMe#44]
Codeship isn't currently working, because it apparently needs to be migrated to a new version.

**Comment by samgqroberts** [comment]
@rjdellecese any progresserino?

**Comment by rjdellecese** [comment]
🤷‍♂ I don't think so. But we should get CI up ASAP if we're going to be developing the project, so I'll look into it again soon!

**Comment by samgqroberts** [comment]
:clap:
